export enum ArticlesRoutes {
  vpnSetup = 'vpn-setup',
  fileServer = 'file-server',
  webServer = 'web-server',
  mailService = 'mail-service',
  termialServer = ' termial-server',
  domainController = 'domain-controller',
  asteriskServer = 'asterisk-server',
  virtualMachineServer = 'virtual-machine-server',
  vds = 'vds',
  backupServer = 'backup-server',
  videoSurveillanceServer = 'video-surveillance-server',
  updateServer = 'update-server',
  printServer = 'print-server',
  virusRemovalDecryptingFiles = 'virus-removal-decrypting-files',
  networkSetup = 'network-setup',
  mikrotikCiscoSetup = 'mikrotik-cisco-setup',
  pcServerAssambly = 'pc-server-assambly',
  zabbixServer = 'zabbix-server',
  installingSoftware = 'installing-software',
  pcUpgrade = 'pc-upgrade',
  consultation = 'consultation',
  networkDesign = 'network-design',
  wifiSetup = 'wifi-setup',
}
